/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/me": {
    /** Return the connect user profile */
    get: operations["getMe"];
  };
  "/users/{username}": {
    /** Return a public profile */
    get: operations["getUserProfile"];
    parameters: {
      path: {
        /** @description Profile username */
        username: string;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description An API Error response */
    Error: {
      /** @description A printable message for this error */
      message?: string;
    };
    /** @description User public profile */
    User: {
      /** @description User unique identifier */
      id?: string;
      /** @description User username */
      username?: string;
    };
    /** @description Score of a user */
    Score: {
      /** @description Score unique identifier */
      id?: string;
      /** @description Title of the score */
      title?: string;
      /**
       * Format: date-time
       * @description Date when the score was created
       */
      creationDate?: string;
      /**
       * @description Privacy of the score
       * @enum {string}
       */
      privacy?: "public" | "private";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Return the connect user profile */
  getMe: {
    responses: {
      /** @description User profile */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Return a public profile */
  getUserProfile: {
    parameters: {
      path: {
        /** @description Profile username */
        username: string;
      };
    };
    responses: {
      /** @description User profile */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description User not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Error */
      default: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
